services:
  app:
    environment:
      APP_ALLOWED_HOSTS: vibe-check.thatcanadian.dev

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yml run
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./cloudflare-tunnel.yml:/etc/cloudflared/config.yml:ro
      - ./cloudflare:/etc/cloudflared/creds:ro
