import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Activity, ArrowUpRight, Building2, CheckCircle2, Copy, Cpu, Database, Gauge, HardDrive, LoaderCircle, RefreshCw, Users } from 'lucide-react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { requestJson } from '@/lib/api';
import type { Invitation } from '@/lib/workspace-api';
import { Button, buttonVariants } from './ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Input } from './ui/input';
import { Badge } from './ui/badge';

type Stats = { reviews: number; completed: number; failed: number; pending: number; flagged: number };
type Instance = { instanceId: string; updatedAt: number; active: number; pending: number; workers: number; cpuPercent?: number; memoryBytes?: number; memoryLimitBytes?: number };
type Platform = {
  observed_at: number;
  convex: { status: string; latency_ms: number | null };
  cloudflare?: { status: string; backend_latency_ms: number; configured_shards: number; active_slot: string };
  backend: { status: string; instance_id: string; queue: { active: number; pending: number; workers: number } };
  overview: null | { observedAt: number; sampleLimit: number; sampledOfferResults: number; publishers: number; instances: Instance[]; traffic: { hour: number; requests: number; errors: number }[]; reviews: { sampled: number; complete: number; failed: number; pending: number }; processing: { sampleSize: number; medianMs: number | null; p95Ms: number | null; p95QueueWaitMs: number | null; failed: number }; advertisers: (Stats & { clientId: string; publishers: (Stats & { publisherId: string; name: string; status: string })[] })[] };
};
const names: Record<string, string> = { kissterra: 'Kissterra', 'smart-financial': 'Smart Financial', 'lead-economy': 'Lead Economy', acp: 'Auto Coverage Pro' };
const seconds = (value: number | null | undefined) => value == null ? 'No samples' : `${(value / 1000).toFixed(1)}s`;
export function PlatformDashboard() {
  const query = useQuery({ queryKey: ['platform'], queryFn: () => requestJson<Platform>('/api/admin/platform'), refetchInterval: 30_000, retry: 1 });
  const [invite, setInvite] = useState<Invitation | null>(null);
  const [copied, setCopied] = useState(false);
  const [resetOpen, setResetOpen] = useState(false);
  const setup = useMutation({ mutationFn: () => requestJson<Invitation>('/api/admin/digital-nudge/invite', { method: 'POST' }), onSuccess: value => { setInvite(value); setResetOpen(false); } });
  const data = query.data;
  const overview = data?.overview;
  const fresh = overview?.instances.filter(instance => Date.now() - instance.updatedAt < 180000) ?? [];
  const active = fresh.reduce((sum, instance) => sum + instance.active, 0);
  const queued = fresh.reduce((sum, instance) => sum + instance.pending, 0);
  const workers = fresh.reduce((sum, instance) => sum + instance.workers, 0);
  const telemetryReady = fresh.length > 0;
  const stressed = fresh.some(instance => (instance.cpuPercent ?? 0) >= 85 || (instance.memoryLimitBytes && (instance.memoryBytes ?? 0) / instance.memoryLimitBytes >= .85)) || (workers > 0 && active >= workers && queued > 0);
  const traffic = overview?.traffic.map(point => ({ ...point, label: new Date(point.hour).toLocaleTimeString([], { hour: '2-digit' }) })) ?? [];
  return <div className="grid gap-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">AdChecked · Platform administration</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Platform overview</h1><p className="mt-2 text-sm text-muted-foreground">Service health, processing load, and activity across advertisers and publishers.</p></div><Button variant="outline" onClick={() => void query.refetch()} disabled={query.isFetching}><RefreshCw className={query.isFetching ? 'animate-spin' : ''} />Refresh</Button></div>
    {query.error ? <div role="alert" className="rounded-xl border border-destructive p-5 text-sm text-destructive">Platform metrics could not be loaded: {query.error.message}</div> : null}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Database} title="Convex backend" value={data?.convex.status === 'reachable' ? 'Connected' : query.isLoading ? 'Checking…' : 'Unavailable'} detail={data?.convex.latency_ms != null ? `${data.convex.latency_ms} ms query round trip` : 'Live query from the application backend'} /><Metric icon={Activity} title="Cloudflare edge" value={data?.cloudflare?.status === 'reachable' ? 'Responding' : 'Not measured'} detail={data?.cloudflare ? `${data.cloudflare.configured_shards} configured container shards · ${data.cloudflare.backend_latency_ms} ms backend round trip` : 'Edge measurements appear on the deployed app'} /><Metric icon={Gauge} title="Processing load" value={!telemetryReady ? 'Awaiting samples' : stressed ? 'High load' : 'Within capacity'} detail={telemetryReady ? `${active} active · ${queued} queued · ${workers} live worker slots` : 'Awake containers report every 60 seconds'} /><Metric icon={Users} title="Network" value={overview ? `${overview.advertisers.length} advertisers` : 'Loading…'} detail={overview ? `${overview.publishers} publisher workspaces, including Digital Nudge` : 'Across all advertiser accounts'} /></div>
    <div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><Card><CardHeader><CardTitle>Backend request traffic</CardTitle><CardDescription>Hourly requests and server errors reported by awake containers. Last 24 hours; collection starts with this release. Static page traffic is in Cloudflare Analytics.</CardDescription></CardHeader><CardContent>{traffic.length ? <div className="h-64 min-w-0"><ResponsiveContainer width="100%" height="100%"><LineChart data={traffic}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" fontSize={11} /><YAxis allowDecimals={false} fontSize={11} /><Tooltip /><Line dataKey="requests" name="Requests" stroke="#059669" strokeWidth={2} dot={traffic.length === 1} /><Line dataKey="errors" name="Server errors" stroke="#dc2626" strokeWidth={2} /></LineChart></ResponsiveContainer></div> : <div className="grid h-64 place-items-center text-center text-sm text-muted-foreground">Traffic history will appear after the first container heartbeat.</div>}</CardContent></Card><Card><CardHeader><CardTitle>Review processing</CardTitle><CardDescription>{overview?.processing.sampleSize ?? 0} most recent measured jobs across the platform.</CardDescription></CardHeader><CardContent className="grid gap-4"><Stat label="Median processing time" value={seconds(overview?.processing.medianMs)} /><Stat label="95th percentile processing" value={seconds(overview?.processing.p95Ms)} /><Stat label="95th percentile queue wait" value={seconds(overview?.processing.p95QueueWaitMs)} /><Stat label="Failed jobs in timing sample" value={overview ? String(overview.processing.failed) : '—'} /></CardContent></Card></div>
    <Card><CardHeader><CardTitle>Container health & capacity</CardTitle><CardDescription>CPU is measured against the container’s CPU allowance; memory comes from its runtime limits. A heartbeat older than 3 minutes is stale and may indicate a sleeping or replaced container.</CardDescription></CardHeader><CardContent>{fresh.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{fresh.map(instance => <div key={instance.instanceId} className="grid gap-3 rounded-xl border p-4"><p className="flex items-center justify-between text-sm font-medium"><span>Instance {instance.instanceId.slice(0, 8)}</span><Badge variant="outline">Reporting</Badge></p><Stat label="CPU" value={instance.cpuPercent == null ? 'Not exposed by runtime' : `${instance.cpuPercent.toFixed(1)}%`} /><Stat label="Memory" value={instance.memoryBytes == null ? 'Not exposed by runtime' : `${Math.round(instance.memoryBytes / 1048576)} MB${instance.memoryLimitBytes ? ` / ${Math.round(instance.memoryLimitBytes / 1048576)} MB` : ''}`} /><Stat label="Active / queued" value={`${instance.active} / ${instance.pending}`} /><p className="text-xs text-muted-foreground">Updated {new Date(instance.updatedAt).toLocaleTimeString()}</p></div>)}</div> : <p className="py-6 text-sm text-muted-foreground">Waiting for the first heartbeat. Current backend reports {data?.backend.queue.active ?? 0} active and {data?.backend.queue.pending ?? 0} queued jobs.</p>}<p className="mt-4 text-xs text-muted-foreground">{(overview?.instances.length ?? 0) - fresh.length} stale instance records in the last 24 hours. Convex CPU, database bandwidth, and Cloudflare edge CPU are available in the provider consoles.</p><div className="mt-4 flex flex-wrap gap-3"><a href="https://dashboard.convex.dev" target="_blank" rel="noreferrer" className={buttonVariants({ size: 'sm', variant: 'outline' })}><Database />Convex dashboard<ArrowUpRight /></a><a href="https://dash.cloudflare.com" target="_blank" rel="noreferrer" className={buttonVariants({ size: 'sm', variant: 'outline' })}><HardDrive />Cloudflare analytics<ArrowUpRight /></a></div></CardContent></Card>
    <section className="grid gap-4"><div><h2 className="text-xl font-semibold">Advertisers & publishers</h2><p className="mt-2 text-sm text-muted-foreground">Latest {overview?.sampledOfferResults ?? 0} offer results, capped at {overview?.sampleLimit ?? 1000}. One creative can be reviewed against several offers. Counts below describe this sample.</p></div>{overview?.advertisers.map(advertiser => <Card key={advertiser.clientId}><CardHeader><CardTitle className="flex items-center gap-2"><Building2 className="size-5" />{names[advertiser.clientId] ?? advertiser.clientId}</CardTitle><CardDescription>{advertiser.reviews} reviews · {advertiser.completed} complete · {advertiser.pending} processing · {advertiser.failed} failed · {advertiser.flagged} flagged</CardDescription></CardHeader><CardContent>{advertiser.publishers.length ? <div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-muted-foreground"><th className="py-3 font-medium">Publisher</th><th>Reviews</th><th>Processing</th><th>Failed</th><th>Access</th></tr></thead><tbody>{advertiser.publishers.map(publisher => <tr key={publisher.publisherId} className="border-b last:border-0"><td className="py-3 font-medium">{publisher.name}</td><td>{publisher.reviews}</td><td>{publisher.pending}</td><td>{publisher.failed}</td><td><Badge variant="outline">{publisher.status}</Badge></td></tr>)}</tbody></table></div> : <p className="text-sm text-muted-foreground">No publisher workspaces yet.</p>}</CardContent></Card>)}</section>
    <Card><CardHeader><CardTitle>Digital Nudge publisher access</CardTitle><CardDescription>Your company has its own publisher identity under each advertiser. Use one publisher login to switch between those advertiser workspaces.</CardDescription></CardHeader><CardContent className="grid gap-4"><div className="flex flex-wrap gap-3"><a href="/publisher" className={buttonVariants()}><Cpu />Open Digital Nudge operations</a><a href="https://app.adchecked.com/login" className={buttonVariants({ variant: 'outline' })}>Open publisher portal</a><Button variant="outline" onClick={() => setResetOpen(true)}>Create publisher setup link</Button></div><p className="text-xs text-muted-foreground">Drive, Telegram, live scans, and existing upload history remain available in Digital Nudge operations. Other publisher teams use direct uploads.</p>{resetOpen ? <div className="rounded-xl border p-4"><p className="text-sm">A new setup link resets Digital Nudge’s publisher login. Existing publisher sessions will be signed out; platform admin access stays available.</p><div className="mt-3 flex gap-2"><Button variant="outline" onClick={() => setResetOpen(false)}>Cancel</Button><Button variant="destructive" disabled={setup.isPending} onClick={() => setup.mutate()}>{setup.isPending ? <LoaderCircle className="animate-spin" /> : <CheckCircle2 />}Create setup link</Button></div></div> : null}{invite ? <div className="grid gap-2 rounded-xl border p-4"><p className="text-sm font-medium">Username: {invite.username}</p><p className="text-xs text-muted-foreground">Choose your password using this link within 7 days.</p><div className="flex flex-wrap gap-2"><Input aria-label="Digital Nudge setup link" className="min-w-0 flex-1" readOnly value={invite.invite_url} onFocus={event => event.target.select()} /><Button variant="outline" onClick={() => void navigator.clipboard.writeText(invite.invite_url).then(() => setCopied(true)).catch(() => setCopied(false))}><Copy />{copied ? 'Copied' : 'Copy'}</Button></div></div> : null}{setup.error ? <p role="alert" className="text-sm text-destructive">{setup.error.message}</p> : null}</CardContent></Card>
    <p className="text-xs text-muted-foreground">{data ? `Last checked ${new Date(data.observed_at).toLocaleTimeString()}. Dashboard refreshes every 30 seconds.` : 'Checking platform…'}</p>
  </div>;
}
function Stat({ label, value }: { label: string; value: string }) { return <div className="flex items-start justify-between gap-4 text-sm"><span className="text-muted-foreground">{label}</span><span className="text-right font-medium tabular-nums">{value}</span></div>; }
function Metric({ icon: Icon, title, value, detail }: { icon: typeof Users; title: string; value: string; detail: string }) { return <Card><CardContent className="grid gap-3 pt-5"><p className="flex items-center gap-2 text-sm font-medium text-muted-foreground"><Icon className="size-4" />{title}</p><p className="text-2xl font-semibold tracking-tight">{value}</p><p className="text-xs leading-5 text-muted-foreground">{detail}</p></CardContent></Card>; }
