"""Export the existing FastAPI response models for container-free Worker reads."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'backend'))

from pydantic import BaseModel, TypeAdapter
from app.review_pipeline import models

TARGET = ROOT / 'worker' / 'read-models.generated.ts'


def render() -> str:
    schemas = {}
    for model in (models.JobRecord, models.ComplianceReport):
        schema = model.model_json_schema()
        schemas.update(schema.pop('$defs', {}))
        schemas[model.__name__] = schema
    # JSON Schema omits default_factory values. Export their actual JSON values
    # too, so old reports retain exactly the defaults FastAPI currently applies.
    for name, schema in schemas.items():
        model = getattr(models, name, None)
        if isinstance(model, type) and issubclass(model, BaseModel):
            for key, field in model.model_fields.items():
                if not field.is_required():
                    schema['properties'][key]['default'] = TypeAdapter(field.annotation).dump_python(
                        field.get_default(call_default_factory=True), mode='json')

    def clean(value):
        if isinstance(value, list):
            return [clean(item) for item in value]
        if not isinstance(value, dict):
            return value
        return {key: (item if key == 'default' else
                      {name: clean(field) for name, field in item.items()} if key == 'properties' else clean(item))
                for key, item in value.items() if key not in {'title', 'description', 'required'}}

    lines = [
        '// Generated by scripts/generate-read-contract.py; do not edit by hand.',
        "import type { ResponseSchema } from './read-contract.ts';",
        'export const readModels: Record<string, ResponseSchema> = {',
    ]
    for name, schema in sorted(schemas.items()):
        schema = clean(schema)
        properties = schema.pop('properties', None)
        if properties is None:
            lines.append(f'  {json.dumps(name)}: {json.dumps(schema)},')
        else:
            lines.append(f'  {json.dumps(name)}: {{ type: "object", properties: {{')
            for key, field in properties.items():
                lines.append(f'    {json.dumps(key)}: {json.dumps(field)},')
            lines.append('  } },')
    lines.append('};\n')
    return '\n'.join(lines)


if __name__ == '__main__':
    if '--check' in sys.argv:
        if TARGET.read_text() != render():
            raise SystemExit('Worker response models are stale. Run scripts/generate-read-contract.py.')
    else:
        TARGET.write_text(render())
