import { requestJson, type ClientSession, type ClientReviewItem, type OfferResult, type ReviewEvidenceFrame } from './api';
export type Publisher = { managedLogin?: boolean; publisherId: string; name: string; username: string; status: 'invited' | 'active' | 'suspended'; createdAt: number; inviteExpiresAt: number | null };
export type Invitation = { publisher_id: string; username: string; invite_url: string };
export type Submission = { released: boolean; jobId: string; publisherId: string; fileName: string; status: string; progress: number; message: string; createdAt: number };
export type Plan = { clientId: string; plan: 'pilot' | 'starter' | 'growth' | 'enterprise'; publisherLimit: number; monthlyReviewLimit: number; monthlyReviews: number; publishers: number };
export type SharedLink = { shareId: string; title: string; createdAt: number; expiresAt: number; revokedAt: number | null; count: number };
export type SharedDetail = { review: ClientReviewItem; report: OfferResult; media_url: string; evidence_frames: ReviewEvidenceFrame[] };
const json = (body: unknown, method = 'POST') => ({ method, headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) });
const base = (clientId: string) => `/api/client/${encodeURIComponent(clientId)}`;
const shares = (clientId?: string) => clientId ? `${base(clientId)}/shares` : '/api/shares';
export const listPublishers = (clientId: string) => requestJson<Publisher[]>(`${base(clientId)}/publishers`);
export const createPublisher = (clientId: string, name: string) => requestJson<Invitation>(`${base(clientId)}/publishers`, json({ name }));
export const invitePublisher = (clientId: string, publisherId: string) => requestJson<Invitation>(`${base(clientId)}/publishers/${publisherId}/invite`, { method: 'POST' });
export const suspendPublisher = (clientId: string, publisherId: string) => requestJson(`${base(clientId)}/publishers/${publisherId}`, { method: 'DELETE' });
export const listSubmissions = (clientId: string, publisherId?: string) => requestJson<Submission[]>(`${base(clientId)}/submissions${publisherId && publisherId !== 'all' ? `?publisher_id=${encodeURIComponent(publisherId)}` : ''}`);
export const getPlan = (clientId: string) => requestJson<Plan>(`${base(clientId)}/plan`);
export const getInvite = (token: string) => requestJson<{ name: string; advertiser: string; username: string }>(`/api/client/invitations/${encodeURIComponent(token)}`);
export const acceptInvite = (token: string, password: string) => requestJson<ClientSession>('/api/client/invitations/accept', json({ token, password }));
export const createShare = (jobIds: string[], clientId?: string, offerId?: string) => requestJson<{ share_id: string; url: string }>(shares(clientId), json({ job_ids: jobIds, title: jobIds.length === 1 ? 'Creative review' : `${jobIds.length} creative reviews`, offer_id: offerId, expires_in_days: 30 }));
export const listShares = (clientId?: string) => requestJson<SharedLink[]>(shares(clientId));
export const revokeShare = (shareId: string, clientId?: string) => requestJson(`${shares(clientId)}/${shareId}`, { method: 'DELETE' });
export const getSharedCollection = (token: string) => requestJson<{ title: string; expires_at: number; job_ids: string[] }>(`/api/public/shares/${encodeURIComponent(token)}`);
export const getSharedDetail = (token: string, jobId: string) => requestJson<SharedDetail>(`/api/public/shares/${encodeURIComponent(token)}/reviews/${jobId}`);
export const getAdminPlans = () => requestJson<(Plan & { name: string })[]>('/api/admin/workspaces');
export const setAdminPlan = (clientId: string, plan: Plan['plan'], publisherLimit: number, monthlyReviewLimit: number) => requestJson(`/api/admin/workspaces/${clientId}/plan`, json({ plan, publisher_limit: publisherLimit, monthly_review_limit: monthlyReviewLimit }, 'PUT'));
